import type { KnowledgeMajor } from '../types';

export type KnowledgeMajorMetadata = Pick<
  KnowledgeMajor,
  'code' | 'slug' | 'title' | 'icon' | 'order'
>;

export const knowledgeMajorMetadata = [
  {
    code: '01',
    slug: 'personal-finance',
    title: '金钱、个人财务与投资生存线',
    icon: 'solar:wallet-bold',
    order: 1,
  },
  {
    code: '02',
    slug: 'math-risk-return',
    title: '数学语言、复利与风险收益',
    icon: 'solar:chart-square-bold',
    order: 2,
  },
  {
    code: '03',
    slug: 'economics-social-system',
    title: '经济学直觉与社会运行',
    icon: 'solar:earth-bold',
    order: 3,
  },
  {
    code: '04',
    slug: 'money-credit-financial-system',
    title: '货币、信用、银行与金融体系',
    icon: 'solar:library-bold',
    order: 4,
  },
  {
    code: '05',
    slug: 'macroeconomics-policy-data',
    title: '宏观经济、政策与数据解读',
    icon: 'solar:graph-up-bold',
    order: 5,
  },
  {
    code: '06',
    slug: 'financial-history-market-cycles',
    title: '金融史、市场周期与危机',
    icon: 'solar:history-bold',
    order: 6,
  },
  {
    code: '07',
    slug: 'financial-assets-capital-markets',
    title: '金融资产与资本市场全景',
    icon: 'solar:pie-chart-2-bold',
    order: 7,
  },
  {
    code: '08',
    slug: 'stocks-listed-companies-shareholder-system',
    title: '股票、上市公司与股东制度',
    icon: 'solar:buildings-2-bold',
    order: 8,
  },
  {
    code: '09',
    slug: 'funds-index-passive-investing',
    title: '基金、指数与被动投资',
    icon: 'solar:chart-2-bold',
    order: 9,
  },
  {
    code: '10',
    slug: 'bonds-fixed-income',
    title: '债券与固定收益',
    icon: 'solar:bill-list-bold',
    order: 10,
  },
  {
    code: '11',
    slug: 'real-estate-commodities-fx-alternatives',
    title: '房地产、商品、外汇与另类资产',
    icon: 'solar:buildings-2-bold',
    order: 11,
  },
  {
    code: '12',
    slug: 'a-share-market-system-account-practice',
    title: 'A 股市场制度与账户实务',
    icon: 'solar:chart-2-bold',
    order: 12,
  },
  {
    code: '13',
    slug: 'global-markets-cross-border-investing',
    title: '全球市场与跨境投资',
    icon: 'solar:global-bold',
    order: 13,
  },
  {
    code: '14',
    slug: 'order-book-market-microstructure',
    title: '订单、盘口与市场微观结构',
    icon: 'solar:bill-list-bold',
    order: 14,
  },
  {
    code: '15',
    slug: 'leverage-shorts-futures-options-derivatives',
    title: '杠杆、卖空、期货、期权与其他衍生品',
    icon: 'solar:shield-warning-bold',
    order: 15,
  },
  {
    code: '16',
    slug: 'accounting-financial-statements',
    title: '会计基础与三张财务报表',
    icon: 'solar:bill-list-bold',
    order: 16,
  },
  {
    code: '17',
    slug: 'financial-analysis-earnings-quality-fraud-detection',
    title: '财务分析、盈利质量与造假识别',
    icon: 'solar:chart-square-bold',
    order: 17,
  },
  {
    code: '18',
    slug: 'corporate-finance-governance-capital-allocation',
    title: '公司金融、治理与资本配置',
    icon: 'solar:case-round-bold',
    order: 18,
  },
  {
    code: '19',
    slug: 'business-valuation-expected-returns',
    title: '企业估值与预期收益',
    icon: 'solar:graph-up-bold',
    order: 19,
  },
  {
    code: '20',
    slug: 'industry-research-value-chain-analysis',
    title: '行业研究与产业链分析',
    icon: 'solar:buildings-2-bold',
    order: 20,
  },
  {
    code: '21',
    slug: 'company-research-investment-thesis',
    title: '公司研究与投资论点',
    icon: 'solar:document-text-bold',
    order: 21,
  },
  {
    code: '22',
    slug: 'behavioral-finance-narratives-decision-science',
    title: '行为金融、市场叙事与决策科学',
    icon: 'solar:users-group-rounded-bold',
    order: 22,
  },
  {
    code: '23',
    slug: 'probability-statistics-scientific-inference',
    title: '概率统计与科学推断',
    icon: 'solar:chart-2-bold',
    order: 23,
  },
  {
    code: '24',
    slug: 'programming-sql-reproducible-research',
    title: '编程、SQL 与可复现研究',
    icon: 'solar:code-square-bold',
    order: 24,
  },
  {
    code: '25',
    slug: 'financial-data-governance-engineering',
    title: '金融数据认知、治理与工程',
    icon: 'solar:database-bold',
    order: 25,
  },
  {
    code: '26',
    slug: 'time-series-financial-econometrics',
    title: '时间序列与金融计量',
    icon: 'solar:chart-2-bold',
    order: 26,
  },
  {
    code: '27',
    slug: 'empirical-research-design-causal-inference',
    title: '实证研究设计与因果推断',
    icon: 'solar:document-text-bold',
    order: 27,
  },
  {
    code: '28',
    slug: 'asset-pricing-factors-risk-premia',
    title: '资产定价、因子与风险溢价',
    icon: 'solar:chart-2-bold',
    order: 28,
  },
  {
    code: '29',
    slug: 'systematic-strategy-taxonomy-signal-design',
    title: '系统化策略谱系与信号设计',
    icon: 'solar:chart-square-bold',
    order: 29,
  },
  {
    code: '30',
    slug: 'backtesting-simulation-evidence-strength',
    title: '回测、仿真与证据强度',
    icon: 'solar:chart-square-bold',
    order: 30,
  },
  {
    code: '31',
    slug: 'financial-machine-learning-text-alternative-data',
    title: '金融机器学习、文本与另类数据',
    icon: 'solar:code-square-bold',
    order: 31,
  },
  {
    code: '32',
    slug: 'portfolio-asset-allocation-performance-attribution',
    title: '投资组合、资产配置与绩效归因',
    icon: 'solar:pie-chart-2-bold',
    order: 32,
  },
  {
    code: '33',
    slug: 'risk-management-stress-testing-capital-survival',
    title: '风险管理、压力测试与资本生存',
    icon: 'solar:shield-warning-bold',
    order: 33,
  },
  {
    code: '34',
    slug: 'trade-execution-cost-capacity',
    title: '交易执行、成本与容量',
    icon: 'solar:chart-square-bold',
    order: 34,
  },
  {
    code: '35',
    slug: 'research-to-production-operations-review',
    title: '从研究到实盘、运营与复盘',
    icon: 'solar:server-square-bold',
    order: 35,
  },
  {
    code: '36',
    slug: 'legal-compliance-ethics-account-security',
    title: '法律合规、职业伦理与账户安全',
    icon: 'solar:shield-check-bold',
    order: 36,
  },
] satisfies KnowledgeMajorMetadata[];

export const knowledgeMajorMetadataByCode = Object.fromEntries(
  knowledgeMajorMetadata.map((major) => [major.code, major])
) as Record<string, KnowledgeMajorMetadata>;
