import {
  _id,
  _price,
  _times,
  _company,
  _boolean,
  _fullName,
  _taskNames,
  _postTitles,
  _description,
  _productNames,
} from './_mock';

// ----------------------------------------------------------------------

export const _myAccount = {
  displayName: 'Jaydon Frankie',
  email: 'demo@minimals.cc',
  photoURL: '/assets/images/avatar/avatar-25.webp',
};

// ----------------------------------------------------------------------

export const _users = [...Array(24)].map((_, index) => ({
  id: _id(index),
  name: _fullName(index),
  company: _company(index),
  isVerified: _boolean(index),
  avatarUrl: `/assets/images/avatar/avatar-${index + 1}.webp`,
  status: index % 4 ? 'active' : 'banned',
  role:
    [
      'Leader',
      'Hr Manager',
      'UI Designer',
      'UX Designer',
      'UI/UX Designer',
      'Project Manager',
      'Backend Developer',
      'Full Stack Designer',
      'Front End Developer',
      'Full Stack Developer',
    ][index] || 'UI Designer',
}));

// ----------------------------------------------------------------------

export const _posts = [...Array(23)].map((_, index) => ({
  id: _id(index),
  title: _postTitles(index),
  description: _description(index),
  coverUrl: `/assets/images/cover/cover-${index + 1}.webp`,
  totalViews: 8829,
  totalComments: 7977,
  totalShares: 8556,
  totalFavorites: 8870,
  postedAt: _times(index),
  author: {
    name: _fullName(index),
    avatarUrl: `/assets/images/avatar/avatar-${index + 1}.webp`,
  },
}));

// ----------------------------------------------------------------------

const COLORS = [
  '#00AB55',
  '#000000',
  '#FFFFFF',
  '#FFC0CB',
  '#FF4842',
  '#1890FF',
  '#94D82D',
  '#FFC107',
];

export const _products = [...Array(24)].map((_, index) => {
  const setIndex = index + 1;

  return {
    id: _id(index),
    price: _price(index),
    name: _productNames(index),
    priceSale: setIndex % 3 ? null : _price(index),
    coverUrl: `/assets/images/product/product-${setIndex}.webp`,
    colors:
      (setIndex === 1 && COLORS.slice(0, 2)) ||
      (setIndex === 2 && COLORS.slice(1, 3)) ||
      (setIndex === 3 && COLORS.slice(2, 4)) ||
      (setIndex === 4 && COLORS.slice(3, 6)) ||
      (setIndex === 23 && COLORS.slice(4, 6)) ||
      (setIndex === 24 && COLORS.slice(5, 6)) ||
      COLORS,
    status:
      ([1, 3, 5].includes(setIndex) && 'sale') || ([4, 8, 12].includes(setIndex) && 'new') || '',
  };
});

// ----------------------------------------------------------------------

export const _timeline = [...Array(5)].map((_, index) => ({
  id: _id(index),
  title: [
    '1983, orders, $4220',
    '12 Invoices have been paid',
    'Order #37745 from September',
    'New order placed #XF-2356',
    'New order placed #XF-2346',
  ][index],
  type: `order${index + 1}`,
  time: _times(index),
}));

export const _traffic = [
  {
    value: 'facebook',
    label: 'Facebook',
    total: 19500,
  },
  {
    value: 'google',
    label: 'Google',
    total: 91200,
  },
  {
    value: 'linkedin',
    label: 'Linkedin',
    total: 69800,
  },
  {
    value: 'twitter',
    label: 'Twitter',
    total: 84900,
  },
];

export const _tasks = Array.from({ length: 5 }, (_, index) => ({
  id: _id(index),
  name: _taskNames(index),
}));

// ----------------------------------------------------------------------

// ----------------------------------------------------------------------

export const _stocks = [
  {
    tsCode: '600519.SH',
    symbol: '600519',
    name: '贵州茅台',
    exchange: 'SSE',
    market: '主板',
    industry: '饮料',
    area: '贵州',
    listStatus: 'L',
    pctChg: 1.85,
    peTtm: 28.4,
    pb: 9.12,
    dvTtm: 1.82,
    totalMv: 234560000,
    circMv: 234560000,
    turnoverRate: 0.23,
    close: 1865.5,
  },
  {
    tsCode: '000858.SZ',
    symbol: '000858',
    name: '五粮液',
    exchange: 'SZSE',
    market: '主板',
    industry: '饮料',
    area: '四川',
    listStatus: 'L',
    pctChg: 0.97,
    peTtm: 19.6,
    pb: 5.43,
    dvTtm: 2.35,
    totalMv: 98730000,
    circMv: 98730000,
    turnoverRate: 0.31,
    close: 127.8,
  },
  {
    tsCode: '600036.SH',
    symbol: '600036',
    name: '招商银行',
    exchange: 'SSE',
    market: '主板',
    industry: '银行',
    area: '广东',
    listStatus: 'L',
    pctChg: 0.55,
    peTtm: 6.8,
    pb: 0.89,
    dvTtm: 4.21,
    totalMv: 93200000,
    circMv: 88900000,
    turnoverRate: 0.45,
    close: 36.5,
  },
  {
    tsCode: '601318.SH',
    symbol: '601318',
    name: '中国平安',
    exchange: 'SSE',
    market: '主板',
    industry: '保险',
    area: '广东',
    listStatus: 'L',
    pctChg: -0.72,
    peTtm: 9.3,
    pb: 1.05,
    dvTtm: 3.88,
    totalMv: 87650000,
    circMv: 87650000,
    turnoverRate: 0.62,
    close: 48.25,
  },
  {
    tsCode: '000651.SZ',
    symbol: '000651',
    name: '格力电器',
    exchange: 'SZSE',
    market: '主板',
    industry: '家用电器',
    area: '广东',
    listStatus: 'L',
    pctChg: -1.34,
    peTtm: 8.7,
    pb: 2.21,
    dvTtm: 5.12,
    totalMv: 43810000,
    circMv: 43810000,
    turnoverRate: 0.87,
    close: 36.88,
  },
  {
    tsCode: '300750.SZ',
    symbol: '300750',
    name: '宁德时代',
    exchange: 'SZSE',
    market: '创业板',
    industry: '电气设备',
    area: '福建',
    listStatus: 'L',
    pctChg: 2.41,
    peTtm: 22.5,
    pb: 4.67,
    dvTtm: 0.45,
    totalMv: 156780000,
    circMv: 132000000,
    turnoverRate: 1.12,
    close: 256.3,
  },
  {
    tsCode: '000333.SZ',
    symbol: '000333',
    name: '美的集团',
    exchange: 'SZSE',
    market: '主板',
    industry: '家用电器',
    area: '广东',
    listStatus: 'L',
    pctChg: 0.28,
    peTtm: 14.2,
    pb: 3.56,
    dvTtm: 2.96,
    totalMv: 68920000,
    circMv: 68920000,
    turnoverRate: 0.54,
    close: 58.74,
  },
  {
    tsCode: '002594.SZ',
    symbol: '002594',
    name: '比亚迪',
    exchange: 'SZSE',
    market: '主板',
    industry: '汽车',
    area: '广东',
    listStatus: 'L',
    pctChg: 3.15,
    peTtm: 31.8,
    pb: 5.89,
    dvTtm: 0.31,
    totalMv: 143560000,
    circMv: 121300000,
    turnoverRate: 1.56,
    close: 238.6,
  },
  {
    tsCode: '601166.SH',
    symbol: '601166',
    name: '兴业银行',
    exchange: 'SSE',
    market: '主板',
    industry: '银行',
    area: '福建',
    listStatus: 'L',
    pctChg: -0.18,
    peTtm: 4.9,
    pb: 0.61,
    dvTtm: 5.68,
    totalMv: 40230000,
    circMv: 40230000,
    turnoverRate: 0.38,
    close: 19.72,
  },
  {
    tsCode: '600276.SH',
    symbol: '600276',
    name: '恒瑞医药',
    exchange: 'SSE',
    market: '主板',
    industry: '医药',
    area: '江苏',
    listStatus: 'L',
    pctChg: 1.07,
    peTtm: 42.1,
    pb: 6.28,
    dvTtm: 0.82,
    totalMv: 35640000,
    circMv: 35640000,
    turnoverRate: 0.71,
    close: 55.3,
  },
  {
    tsCode: '002415.SZ',
    symbol: '002415',
    name: '海康威视',
    exchange: 'SZSE',
    market: '主板',
    industry: '电子',
    area: '浙江',
    listStatus: 'L',
    pctChg: -0.43,
    peTtm: 18.6,
    pb: 3.14,
    dvTtm: 3.24,
    totalMv: 61870000,
    circMv: 61870000,
    turnoverRate: 0.43,
    close: 29.45,
  },
  {
    tsCode: '600900.SH',
    symbol: '600900',
    name: '长江电力',
    exchange: 'SSE',
    market: '主板',
    industry: '电力',
    area: '湖北',
    listStatus: 'L',
    pctChg: 0.33,
    peTtm: 20.3,
    pb: 3.42,
    dvTtm: 3.91,
    totalMv: 78960000,
    circMv: 78960000,
    turnoverRate: 0.28,
    close: 26.88,
  },
  {
    tsCode: '601398.SH',
    symbol: '601398',
    name: '工商银行',
    exchange: 'SSE',
    market: '主板',
    industry: '银行',
    area: '北京',
    listStatus: 'L',
    pctChg: 0.14,
    peTtm: 5.1,
    pb: 0.58,
    dvTtm: 6.32,
    totalMv: 198400000,
    circMv: 145200000,
    turnoverRate: 0.19,
    close: 5.54,
  },
  {
    tsCode: '300059.SZ',
    symbol: '300059',
    name: '东方财富',
    exchange: 'SZSE',
    market: '创业板',
    industry: '非银金融',
    area: '上海',
    listStatus: 'L',
    pctChg: 2.87,
    peTtm: 26.4,
    pb: 4.83,
    dvTtm: 0.68,
    totalMv: 54320000,
    circMv: 54320000,
    turnoverRate: 1.23,
    close: 19.86,
  },
  {
    tsCode: '600887.SH',
    symbol: '600887',
    name: '伊利股份',
    exchange: 'SSE',
    market: '主板',
    industry: '食品饮料',
    area: '内蒙古',
    listStatus: 'L',
    pctChg: -0.61,
    peTtm: 15.8,
    pb: 3.71,
    dvTtm: 3.15,
    totalMv: 40670000,
    circMv: 40670000,
    turnoverRate: 0.48,
    close: 25.12,
  },
  {
    tsCode: '601288.SH',
    symbol: '601288',
    name: '农业银行',
    exchange: 'SSE',
    market: '主板',
    industry: '银行',
    area: '北京',
    listStatus: 'L',
    pctChg: 0.22,
    peTtm: 4.7,
    pb: 0.53,
    dvTtm: 6.85,
    totalMv: 156900000,
    circMv: 109800000,
    turnoverRate: 0.16,
    close: 4.53,
  },
  {
    tsCode: '000568.SZ',
    symbol: '000568',
    name: '泸州老窖',
    exchange: 'SZSE',
    market: '主板',
    industry: '饮料',
    area: '四川',
    listStatus: 'L',
    pctChg: -0.89,
    peTtm: 17.3,
    pb: 4.92,
    dvTtm: 2.74,
    totalMv: 36580000,
    circMv: 36580000,
    turnoverRate: 0.52,
    close: 95.3,
  },
  {
    tsCode: '000002.SZ',
    symbol: '000002',
    name: '万科A',
    exchange: 'SZSE',
    market: '主板',
    industry: '房地产',
    area: '广东',
    listStatus: 'L',
    pctChg: -2.13,
    peTtm: null,
    pb: 0.37,
    dvTtm: 0,
    totalMv: 21430000,
    circMv: 19820000,
    turnoverRate: 1.34,
    close: 7.28,
  },
  {
    tsCode: '688599.SH',
    symbol: '688599',
    name: '天合光能',
    exchange: 'SSE',
    market: '科创板',
    industry: '电气设备',
    area: '江苏',
    listStatus: 'L',
    pctChg: 4.21,
    peTtm: 15.2,
    pb: 1.84,
    dvTtm: 1.12,
    totalMv: 24560000,
    circMv: 18900000,
    turnoverRate: 2.31,
    close: 13.68,
  },
  {
    tsCode: '002049.SZ',
    symbol: '002049',
    name: '紫光国微',
    exchange: 'SZSE',
    market: '主板',
    industry: '半导体',
    area: '北京',
    listStatus: 'L',
    pctChg: 1.63,
    peTtm: 38.7,
    pb: 5.26,
    dvTtm: 0.56,
    totalMv: 18730000,
    circMv: 17240000,
    turnoverRate: 0.96,
    close: 87.45,
  },
];

// ----------------------------------------------------------------------

export const _notifications = [
  {
    id: _id(1),
    title: 'Your order is placed',
    description: 'waiting for shipping',
    avatarUrl: null,
    type: 'order-placed',
    postedAt: _times(1),
    isUnRead: true,
  },
  {
    id: _id(2),
    title: _fullName(2),
    description: 'answered to your comment on the Minimal',
    avatarUrl: '/assets/images/avatar/avatar-2.webp',
    type: 'friend-interactive',
    postedAt: _times(2),
    isUnRead: true,
  },
  {
    id: _id(3),
    title: 'You have new message',
    description: '5 unread messages',
    avatarUrl: null,
    type: 'chat-message',
    postedAt: _times(3),
    isUnRead: false,
  },
  {
    id: _id(4),
    title: 'You have new mail',
    description: 'sent from Guido Padberg',
    avatarUrl: null,
    type: 'mail',
    postedAt: _times(4),
    isUnRead: false,
  },
  {
    id: _id(5),
    title: 'Delivery processing',
    description: 'Your order is being shipped',
    avatarUrl: null,
    type: 'order-shipped',
    postedAt: _times(5),
    isUnRead: false,
  },
];
